version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: unified_inbox
    ports:
      - '5432:5432' # Ánh xạ cổng 5432 của container ra máy thật
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: